"""Diffusion sampling with Mola (EDM / Karras et al. 2022).

Molecules are generated by integrating the probability-flow ODE from pure noise
(sigma = 80) to sigma = 0, with Euler (10 steps by default) or Heun steps. At a fixed noise
level, the same denoiser also gives a score function that can be followed with Langevin
updates; this is how pseudo-dynamic trajectories are simulated (by default at sigma = 0.9).
"""
import numpy as np
import torch


SIGMA_DATA = 0.3
SIGMA_MIN = 0.002
SIGMA_MAX = 80.0
RHO = 7.0


def append_dims(x, ndim):
    return x[(...,) + (None,) * (ndim - x.ndim)]


def measured_mask(seq):
    """Where Fiber-seq measures each channel, as (n, 2, length) floats for one-hot seq (n, 4, length):
    A/T bases for m6A and both bases of each CpG for methylation. Everywhere else the data are 0."""
    at = (seq[:, 0] + seq[:, 3] > 0.5).float()
    cg = ((seq[:, 1, :-1] > 0.5) & (seq[:, 2, 1:] > 0.5)).float()
    cpg = torch.zeros_like(at)
    cpg[:, :-1] = cg
    cpg[:, 1:] = torch.maximum(cpg[:, 1:], cg)
    return torch.stack([at, cpg], dim=1)


def denoise(model, x, seq, sigma, mask=None):
    """Karras-preconditioned denoiser D(x, sigma | seq). sigma has one value per molecule.

    With a mask (see measured_mask), the denoised molecule is 0 outside it, as the data are. This is
    for models trained with the masked loss, which are not constrained there.
    """
    sigma = append_dims(sigma, x.ndim)
    c_skip = SIGMA_DATA ** 2 / (sigma ** 2 + SIGMA_DATA ** 2)
    c_out = sigma * SIGMA_DATA / (sigma ** 2 + SIGMA_DATA ** 2) ** 0.5
    c_in = 1 / (sigma ** 2 + SIGMA_DATA ** 2) ** 0.5
    t = 0.25 * torch.log(sigma.flatten() + 1e-44)
    out = c_out * model((c_in * x).float(), seq, t.float()) + c_skip * x
    return out if mask is None else out * mask


def karras_sigmas(n, sigma_max=SIGMA_MAX, sigma_min=SIGMA_MIN, rho=RHO, device="cpu"):
    """n noise levels from sigma_max to sigma_min, followed by a final 0."""
    ramp = torch.linspace(0, 1, n)
    sigmas = (sigma_max ** (1 / rho) + ramp * (sigma_min ** (1 / rho) - sigma_max ** (1 / rho))) ** rho
    return torch.cat([sigmas, sigmas.new_zeros(1)]).to(device)


@torch.no_grad()
def euler(model, x, seq, sigmas, mask=None):
    """Euler steps of the probability-flow ODE along the given noise levels."""
    ones = x.new_ones(x.shape[0])
    for i in range(len(sigmas) - 1):
        d = (x - denoise(model, x, seq, sigmas[i] * ones, mask)) / sigmas[i]
        x = x + d * (sigmas[i + 1] - sigmas[i])
    return x


@torch.no_grad()
def heun(model, x, seq, sigmas, mask=None):
    """Heun steps (Karras et al. 2022, Algorithm 1): each Euler step is corrected with the slope at
    its end point, except the last step to sigma = 0. n steps take 2n - 1 network evaluations."""
    ones = x.new_ones(x.shape[0])
    for i in range(len(sigmas) - 1):
        d = (x - denoise(model, x, seq, sigmas[i] * ones, mask)) / sigmas[i]
        x_next = x + d * (sigmas[i + 1] - sigmas[i])
        if sigmas[i + 1] > 0:
            d_next = (x_next - denoise(model, x_next, seq, sigmas[i + 1] * ones, mask)) / sigmas[i + 1]
            x_next = x + 0.5 * (d + d_next) * (sigmas[i + 1] - sigmas[i])
        x = x_next
    return x


SAMPLERS = {"euler": euler, "heun": heun}


def to_tensor(sequence, device):
    """One-hot (length, 4) array -> (1, 4, length) tensor."""
    return torch.as_tensor(np.asarray(sequence)[None], dtype=torch.float32, device=device).transpose(1, 2)


def sample(model, sequence, n, steps=10, batch_size=50, device="cuda", masked=False, sampler="euler"):
    """Generate n molecules for a one-hot sequence of shape (length, 4).

    Returns an array of shape (n, 2, length): channel 0 is m6A (accessibility) and
    channel 1 is CpG methylation, both on the scale of likelihoods divided by 256.
    Values are not clipped and can fall outside [0, 1]. The length must be a multiple
    of 400 (the U-Net pools by 4 * 4 * 5 * 5); Mola was trained on 10 kb.

    sampler is "euler" (the default; `steps` network evaluations per molecule) or "heun"
    (second order; 2 * steps - 1 evaluations), integrating along the Karras schedule of `steps`
    noise levels. masked=True is for models trained with the masked loss: m6A is then generated
    only at A/T bases and methylation only at CpGs, and the molecules are 0 elsewhere.
    """
    integrate = SAMPLERS[sampler]
    seq = to_tensor(sequence, device)
    sigmas = karras_sigmas(steps, device=device)
    mask = measured_mask(seq) if masked else None
    out = []
    for i in range(0, n, batch_size):
        b = min(batch_size, n - i)
        x = torch.randn((b, 2, seq.shape[-1]), device=device) * SIGMA_MAX
        out.append(integrate(model, x, seq.expand(b, -1, -1), sigmas, mask).cpu().numpy())
    return np.concatenate(out)


@torch.no_grad()
def langevin(model, x0, sequence, steps, sigma=0.9, step_size=0.01, clip=10.0, noise=1.0, burn_in=5000,
             readout_steps=1, save_every=1, device="cuda", log_every=1000, masked=False):
    """Fixed-sigma Langevin trajectories started from generated molecules x0 (n, 2, length).

    Every setting except `steps` has a default (the same as the `dynamics` command), and each can
    be changed: `noise` scales the Gaussian noise added at each update (larger values explore more,
    0 leaves only the score-directed drift), `step_size` sets the size of each update, and `sigma`
    the noise level at which the score is evaluated. The molecules are first perturbed with
    Gaussian noise of standard deviation sigma; each update is then

        x <- x + step_size * s(x) + sqrt(2 step_size) * noise * N(0, 1),

    with the score s(x) = (D(x, sigma) - x) / sigma^2 scaled down per molecule to an RMS of at most
    `clip` (0 turns clipping off). After `burn_in` updates, a frame is saved after the first
    update and every `save_every` updates thereafter, for a total of `steps` updates.
    A frame is the clean-state readout of the noisy
    state: one denoiser call D(x, sigma) with readout_steps=1 (the default), or that many Euler
    steps from sigma to 0; readout_steps=0 saves the noisy state itself. The readout never replaces
    the noisy state, from which the chain continues. masked is as in sample().

    Returns unclipped float16 frames of shape (n, 2, length, ceil(steps / save_every)).
    """
    x = torch.as_tensor(x0, device=device)
    n, _, length = x.shape
    seq = to_tensor(sequence, device).expand(n, -1, -1)
    mask = measured_mask(seq) if masked else None
    sigma_vec = x.new_full((n,), sigma)
    readout_sigmas = karras_sigmas(readout_steps, sigma_max=sigma, device=device)
    noise_scale = float(np.sqrt(2.0 * step_size)) * noise

    frames = np.empty((n, 2, length, len(range(0, steps, save_every))), dtype=np.float16)
    x = x + torch.randn_like(x) * sigma
    for k in range(burn_in + steps):
        score = (denoise(model, x, seq, sigma_vec, mask) - x) / sigma ** 2
        rms = score.flatten(1).square().mean(dim=1).sqrt()
        if clip > 0:
            score = score * (clip / rms.clamp_min(1e-12)).clamp(max=1.0).view(-1, 1, 1)
        x = x + step_size * score + noise_scale * torch.randn_like(x)

        saved = k - burn_in
        if saved >= 0 and saved % save_every == 0:
            if readout_steps == 1:
                frame = denoise(model, x, seq, sigma_vec, mask)
            elif readout_steps > 1:
                frame = euler(model, x, seq, readout_sigmas, mask)
            else:
                frame = x
            frames[..., saved // save_every] = frame.cpu().numpy()
        if log_every and (k + 1) % log_every == 0:
            stage = "burn-in" if k < burn_in else "saving"
            print(f"update {k + 1}/{burn_in + steps} ({stage})  score RMS {rms.mean().item():.3g}", flush=True)
    return frames


def training_loss(model, x0, seq, mask=None):
    """Denoising loss with log-normal noise levels and Karras weighting.

    Without a mask the squared error is averaged over every position of both channels, as for the
    released model. With a mask of shape (n, 2, length) it is a weighted average over the positions
    where the mask is non-zero; measured_mask(seq) keeps only A/T bases for m6A and CpGs for
    methylation, the positions Fiber-seq can measure.
    """
    sigma = torch.exp(-1.2 + 1.2 * torch.randn(x0.shape[0], device=x0.device))
    x = x0 + torch.randn_like(x0) * append_dims(sigma, x0.ndim)
    weight = append_dims(sigma ** -2 + 1 / SIGMA_DATA ** 2, x0.ndim)
    error = weight * (denoise(model, x, seq, sigma) - x0) ** 2
    if mask is None:
        return error.mean(dim=(1, 2)).mean()
    return ((error * mask).sum(dim=(1, 2)) / mask.sum(dim=(1, 2)).clamp_min(1)).mean()
